services:
  api:
    build:
      context: .
    container_name: shop-api-app
    depends_on:
      - db
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-5000}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/prisma
    networks:
      - shop-network

  db:
    image: postgres:15-alpine
    container_name: shop-postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME:-shopdb}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-4173}:4173"
    networks:
      - shop-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-shopdb}"]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  shop-network:
    driver: bridge

volumes:
  postgres_data:
